def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]
     
pipeline {
	agent any
	
    environment {
        AWS_REGION = 'us-east-1'
        cluster = "vproprod"
        service = "vproappprodsvc"
    }
	
    stages{
       
        stage('Deploy to ECS Prod') {
            steps {
                script {
                    sh "aws ecs update-service --region ${AWS_REGION} --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }
        }


    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkins-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
